#!/bin/bash
# This creates a Kubernetes secret.
# ex. ./create-secret.sh mysql-root-auth root-password foobar

if [ $# -ne 3 ]; then
  echo usage: create-secret {secret-name} {data-name} {data-value}
  exit 1
fi
secretName=$1
dataName=$2
dataValue=$3
kubectl create secret generic $secretName --from-literal=$dataName=$dataValue
