#!/bin/bash
# This resets the database in Kubernetes.

name=devo-database
podName=$(kubectl get pods | grep $name | cut -d" " -f1)
password=$(./get-secret mysql-root-auth root-password)
kubectl exec -i $podName -- mysql -uroot -p${password} < database/ddl.sql
