#!/bin/bash

echo building Docker image
docker build -t gcr.io/ocismartdevice/devo-server .

echo pushing image to Google Cloud Container Registry
gcloud docker -- push gcr.io/ocismartdevice/devo-server

echo deleting previous pod
kubectl delete deployment devo-server

echo creating pod
kubectl run devo-server --image=gcr.io/ocismartdevice/devo-server --port=3001

echo deleting previous service
kubectl delete service devo-server

echo creating service
kubectl expose deployment devo-server --type=LoadBalancer --port 3001 --target-port 3001

echo see EXTERNAL-IP below
kubectl get service
