#!/bin/bash
# This retreives the value of a Kubernetes secret.
# ex. ./get-secret.sh mysql-root-auth root-password
# ex. ./get-secret.sh mysql-user-auth username

if [ $# -ne 2 ]; then
  echo usage: get-secret {secret-name} {data-name}
  exit 1
fi
secretName=$1
dataName=$2

# jq -r produces raw output rather than
# being formatted as a JSON string with quotes.
filter=".items[] | select(.kind == \"Secret\" and .metadata.name == \"$secretName\") | .data.\"$dataName\""

encodedValue=`kubectl get secrets -ojson | jq -r "$filter"`
echo $encodedValue | base64 --decode
