#!/bin/bash
# This retreives the values of Kubernetes secrets.
# ex. ./get-secret.sh mysql-user-auth

if [ $# -ne 1 ]; then
  echo usage: get-secret {secret-name}
  exit 1
fi
secretName=$1

# jq -r produces raw output rather than
# being formatted as a JSON string with quotes.
filter=".items[] | select(.kind == \"Secret\" and .metadata.name == \"$secretName\") | .data"

encodedValue=`kubectl get secrets -ojson | jq -r "$filter"`
#echo $encodedValue | base64 --decode
echo $encodedValue
