#!/bin/bash
kubectl delete secret mysql-user-auth
kubectl create secret generic mysql-user-auth --from-file=./username.secret --from-file=./password.secret

kubectl delete secret mysql-root-auth
kubectl create secret generic mysql-root-auth --from-file=./root-password.secret
